<?php

/**
 * PluginAlGuestbook
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7200 2010-02-21 09:37:37Z beberlei $
 */
abstract class PluginAlGuestbook extends BaseAlGuestbook
{
    /**
     * Returns a shorter text of the guestbook entries,
     * to use in admin interface.
     *
     * @return string - short text
     */
    public function getShortText()
    {
        return dmString::truncate($this->getText(), 40);
    }
}