generator:
  class: dmAdminDoctrineGenerator
  param:
    model_class: AlGuestbook
    theme: dmAdmin
    non_verbose_templates: true
    with_show: false
    route_prefix: al_guestbook
    with_doctrine_route: false
    config:
      actions: ~
      fields:
        is_active:
          label: Active
      list:
        display:
          - '=author'
          - email
          - website
          - short_text
          - is_active
          - created_at
          - updated_at
        sort:
          - created_at
          - desc
        table_method: getAdminListQuery
        table_count_method: ~
        sortable: false
      filter:
        display:
          - author
          - is_active
          - email
          - website
          - text
          - created_at
          - updated_at
      form:
        display:
          NONE: [author, is_active]
          Text: [text]
          Others: [email, website]
        class: AlGuestbookAdminForm
        fields:
          website: { is_link: true, help: 'Drag & drop a page here from the PAGES panel, or write an url' }
      edit: ~
      new: ~
