all:
    # Settings for alGusetbookPlugin
    al_guestbook:
        # wich css stylsheet is used for the guestbook default al_guestbook.css
        # to add a different css for example new_guestbook.css add this stylesheet
        # to public_html/alGuestbookPlugin/css, and change the use_stylesheet to the new_guestbook.
        use_stylesheet:     al_guestbook
        
        gravatar:
            enabled:          false
            default_size:     40
            default_image:
            default_rating:   G
            cache_expiration: 3 days