
AlGuestbook:
    actAs:
        Timestampable:      {}
    columns:
        author:             { type: string(32), notnull: true }
        email:              { type: string(64) }
        website:            { type: string(64) }
        text:               { type: clob, extra: markdown }
        is_active:          { type: boolean, notnull: true, default: true }